version: '3.8'

volumes:
  datafiles: null
services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_TCP_PORT=3306
    command: --init-file /home/basket.sql
    volumes:
      - datafiles:/var/lib/mysql
      - ./mysql/basket.sql:/home/basket.sql
    restart: always

  website:
    container_name: php73
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      #- MYSQL_DBNAME=
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql
